apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-web-application
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scalable-web-application
  template:
    metadata:
      labels:
        app: scalable-web-application
    spec:
      containers:
      - name: web-app
        image: your-docker-image:latest
        ports:
        - containerPort: 80
